name: CI

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    strategy:
      matrix:
        php: [ '7.3', '7.4', '8.0' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug, intl, zip
          coverage: xdebug
      - name: Get Composer cache dir
        id: cache_dirs
        run: echo "::set-output name=composer_cache::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_dirs.outputs.composer_cache }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/simple-phpunit --configuration phpunit.xml.dist --coverage-text --colors=never
