name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        php: [ 7.3, 7.4, 8.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - name: Get Composer Home
        id: cache_dirs
        run: echo "::set-output name=composer_home::$(composer config home)"
      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_dirs.outputs.composer_home }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run tests
        run: vendor/bin/simple-phpunit --configuration phpunit.xml.dist --coverage-text --colors=never
