name: CI

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    strategy:
      matrix:
        php: [ '7.3', '7.4', '8.0' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: display_errors=On
          extensions: ds, xdebug, intl, pdo_sqlite, zip
          coverage: xdebug
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Get Composer cache dir
        id: cache_dirs
        run: echo "::set-output name=composer_cache::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_dirs.outputs.composer_cache }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-$ {{ secrets.CACHE_VERSION }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-$ {{ secrets.CACHE_VERSION }}-
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/simple-phpunit --configuration phpunit.xml.dist --coverage-text --colors=never

  pages:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/master'}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install sphinx
      - name: Build pages
        run: sphinx-build -n -W --keep-going -b html doc public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/public
